const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('launcher', {
  appVersion: () => ipcRenderer.invoke('app:version'),
  chronaStartup: () => ipcRenderer.invoke('chrona:startup'),
  chronaReady: () => ipcRenderer.invoke('chrona:ready'),
  checkChronaUpdate: () => ipcRenderer.invoke('chrona:check'),
  installChronaUpdate: () => ipcRenderer.invoke('chrona:install'),
  openUpdateLog: () => ipcRenderer.invoke('chrona:logs'),
  acknowledgeRelease: () => ipcRenderer.invoke('chrona:notesSeen'),
  detectSetupLibraries: () => ipcRenderer.invoke('chrona:detectLibraries'),
  pickSetupFolder: () => ipcRenderer.invoke('chrona:pickFolder'),
  completeSetup: value => ipcRenderer.invoke('chrona:completeSetup', value),
  onChronaProgress: callback => ipcRenderer.on('chrona:progress', (_event, value) => callback(value)),
  pickDownloadFolder: (key) => ipcRenderer.invoke('downloads:folder', key),
  addSteamLibraryFolder: () => ipcRenderer.invoke('steam:addLibraryFolder'),
  removeSteamLibraryFolder: (folder) => ipcRenderer.invoke('steam:removeLibraryFolder', folder),
  setFolderExclusions: (enabled) => ipcRenderer.invoke('downloads:exclusions', enabled),
  openDownloadBrowser: (url, game) => ipcRenderer.invoke('downloads:open', url, game),
  startMultipart: (game, url, type, count) => ipcRenderer.invoke('multipart:start', game, url, type, count),
  resumeMultipartType: (game, url, type, count) => ipcRenderer.invoke('multipart:resumeType', game, url, type, count),
  listMultipart: () => ipcRenderer.invoke('multipart:list'),
  confirmMultipart: (id, complete) => ipcRenderer.invoke('multipart:confirm', id, complete),
  onMultipartChanged: callback => ipcRenderer.on('multipart:changed', (_event, session) => callback(session)),
  onMultipartChooseType: callback => ipcRenderer.on('multipart:chooseType', (_event, payload) => callback(payload)),
  onMultipartRequestCount: callback => ipcRenderer.on('multipart:requestCount', (_event, payload) => callback(payload)),
  browserControl: (action) => ipcRenderer.invoke('browser:control', action),
  onDownloadStatus: (callback) => ipcRenderer.on('download:status', (_event, payload) => callback(payload)),
  onDownloadStarted: (callback) => ipcRenderer.on('download:started', (_event, name) => callback(name)),
  controlDownload: (id, action) => ipcRenderer.invoke('downloads:control', id, action),
  dismissDownload: (id) => ipcRenderer.invoke('downloads:dismiss', id),
  retryDownload: (retryId) => ipcRenderer.invoke('downloads:retry', retryId),
  getDownloadHistory: () => ipcRenderer.invoke('downloads:list'),
  revealDownload: id => ipcRenderer.invoke('downloads:reveal', id),
  onDownloadHistoryChanged: callback => ipcRenderer.on('downloads:changed', () => callback()),
  onDownloadUrl: (callback) => ipcRenderer.on('download:url', (_event, url) => callback(url)),
  onLibraryChanged: (callback) => ipcRenderer.on('library:changed', () => callback()),
  getStore: () => ipcRenderer.invoke('store:get'),
  scan: () => ipcRenderer.invoke('library:scan'),
  importSteamLibrary: () => ipcRenderer.invoke('library:importSteam'),
  cancelSteamImport: () => ipcRenderer.invoke('library:cancelSteamImport'),
  detectSteamAccounts: () => ipcRenderer.invoke('steam:detectAccounts'),
  updateSteamAccount: (account) => ipcRenderer.invoke('steam:updateAccount', account),
  addLocation: () => ipcRenderer.invoke('locations:add'),
  removeLocation: (folder) => ipcRenderer.invoke('locations:remove', folder),
  openLocation: (folder) => ipcRenderer.invoke('locations:open', folder),
  addManualGame: () => ipcRenderer.invoke('game:addManual'),
  addCatalogGame: (draft) => ipcRenderer.invoke('game:addCatalog', draft),
  updateGame: (game) => ipcRenderer.invoke('game:update', game),
  deleteGame: (gameId) => ipcRenderer.invoke('game:delete', gameId),
  uninstallGame: (gameId) => ipcRenderer.invoke('game:uninstall', gameId),
  listLaunchers: (gameId) => ipcRenderer.invoke('game:listLaunchers', gameId),
  updateSettings: (settings) => ipcRenderer.invoke('settings:update', settings),
  chooseHomeBackground: () => ipcRenderer.invoke('settings:homeBackground'),
  pickExecutable: () => ipcRenderer.invoke('game:pickExecutable'),
  launchGame: (gameId) => ipcRenderer.invoke('game:launch', gameId),
  getCurrentlyPlaying: () => ipcRenderer.invoke('game:playing'),
  onCurrentlyPlaying: (callback) => ipcRenderer.on('game:playing', (_event, game) => callback(game)),
  installGame: (gameId) => ipcRenderer.invoke('game:install', gameId),
  browseGame: (gameId) => ipcRenderer.invoke('game:browse', gameId),
  verifyGame: (gameId) => ipcRenderer.invoke('game:verify', gameId),
  searchCoverArt: (gameId, query) => ipcRenderer.invoke('cover:search', gameId, query),
  getStoreInfo: (gameId) => ipcRenderer.invoke('store:info', gameId),
  searchStore: (query, filters) => ipcRenderer.invoke('store:search', query, filters),
  getStoreCatalog: (filters) => ipcRenderer.invoke('store:catalog', filters),
  getStoreGameDetails: (game) => ipcRenderer.invoke('store:gameDetails', game),
  findGameLinks: (game) => ipcRenderer.invoke('store:links', game),
  chooseZeigames: () => ipcRenderer.invoke('zeigames:warning'),
  chooseDownloadType: () => ipcRenderer.invoke('multipart:chooseType'),
  checkGameUpdate: (game) => ipcRenderer.invoke('game:checkUpdate', game),
  openStore: (url) => ipcRenderer.invoke('store:open', url),
  minimize: () => ipcRenderer.invoke('window:minimize'),
  maximize: () => ipcRenderer.invoke('window:maximize'),
  close: () => ipcRenderer.invoke('window:close')
});
